# Snapshot report for `built-ins/Temporal/PlainDateTime/prototype/withCalendar/index.js`

The actual snapshot is saved in `index.js.snap`.

Generated by [AVA](https://avajs.dev).

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/argument-string.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/basic.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/branding.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/builtin-calendar-no-observable-calls.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/builtin.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-case-insensitive.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:352:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:272:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:276:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:280:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:364:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:284:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:368:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:288:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:372:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:292:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:376:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:296:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:380:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:300:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:384:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:304:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:388:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:308:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:392:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:312:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:396:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:316:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:400:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:320:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:404:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:324:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:408:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:328:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:412:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:332:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:416:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:336:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:420:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:340:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:424:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:344:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-number.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-string-leap-second.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:352:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:272:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:276:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:280:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:364:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:284:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:368:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:288:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:372:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:292:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:376:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:296:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:380:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:300:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:384:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:304:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:388:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:308:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:392:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:312:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:396:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:316:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:400:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:320:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:404:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:324:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:408:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:328:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:412:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:332:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:416:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:336:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:420:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:340:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:424:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:344:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-string.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:352:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:272:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:276:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:280:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:364:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:284:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:368:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:288:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:372:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:292:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:376:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:296:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:380:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:300:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:384:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:304:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:388:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:308:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:392:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:312:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:396:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:316:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:400:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:320:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:404:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:324:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:408:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:328:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:412:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:332:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:416:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:336:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:420:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:340:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:424:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:344:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-temporal-object.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'BinaryExpressions with operator `<` are not supported at this time',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-wrong-type.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/length.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/missing-argument.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/name.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/not-a-constructor.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/prop-desc.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Temporal/PlainDateTime/prototype/withCalendar/subclassing-ignored.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }
